# Generated by Django 3.2.9 on 2021-12-14 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appCoderFinal', '0003_medico_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=40)),
                ('activo', models.BooleanField()),
                ('profesional', models.BooleanField()),
                ('fechaDeIncorporacion', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='fechaDeIncorporacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
